services:
  frontend:
    build:
      context: ./example/frontend
      dockerfile: Dockerfile
    ports:
      - "6284:80"
    environment:
      - VITE_API_URL=https://youverse.loay.work/api

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python -m app.db.db && python -m app.db.init_tables && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "9923:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=streaming_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local

